# Min-Max Distance Optimization Configuration
# This is a specific configuration for the geometric optimization problem

# General settings
max_iterations: 150                  # More iterations for this harder problem
checkpoint_interval: 15
log_level: "INFO"
random_seed: null                    # Use random seeds for more diversity

# Evolution settings
diff_based_evolution: true
allow_full_rewrites: true            # Allow occasional full rewrites for this problem
max_code_length: 3000

# LLM configuration
llm:
  primary_model: "gemini-2.0-flash"   # Use more powerful model as primary
  primary_model_weight: 0.7
  secondary_model: "gemini-2.0-pro"   # Use most capable model occasionally
  secondary_model_weight: 0.3
  
  # High temperature for creative geometric solutions
  temperature: 0.9
  top_p: 0.95
  max_tokens: 4096

# Prompt configuration
prompt:
  system_message: "You are an expert in computational geometry and mathematical optimization. Your task is to design algorithms that find optimal point configurations with minimal ratio between maximum and minimum pairwise distances."
  
  num_top_programs: 3
  num_diverse_programs: 3
  
  template_variations:
    improvement_focus:
      - "Consider known geometric patterns like Fibonacci spirals or regular polygons."
      - "Think about symmetry and how it affects the distance ratio."
      - "Consider optimization techniques like simulated annealing or gradient descent."
      - "Explore perturbation methods that maintain approximately equal minimum distances."

# Database configuration
database:
  # Large population for diverse geometric solutions
  population_size: 500
  archive_size: 50
  num_islands: 7
  
  # Balance exploration and exploitation
  elite_selection_ratio: 0.15
  exploitation_ratio: 0.6
  exploration_ratio: 0.25
  
  # Use score and stability as feature dimensions
  feature_dimensions:
    - "ratio_score"
    - "stability"

# Evaluator configuration
evaluator:
  # Less strict cascade for this problem
  cascade_evaluation: true
  cascade_thresholds:
    - 0.3                            # First stage: modest performance
    
  # Multiple parallel evaluations for different random seeds
  parallel_evaluations: 6
